export { createServices, createAdminServices } from '@/lib/services/factory'
export type { Services } from '@/lib/services/factory'

export { ProjectService } from '@/lib/services/project.service'
export { TalentService } from '@/lib/services/talent.service'
export type { TalentRow } from '@/lib/services/talent.service'
export { AssignmentService } from '@/lib/services/assignment.service'
export { CRMService } from '@/lib/services/crm.service'
export { WorkflowService } from '@/lib/services/workflow.service'
export type { EmitEventInput } from '@/lib/services/workflow.service'
export { FinanceService } from '@/lib/services/finance.service'
export { AnalyticsService } from '@/lib/services/analytics.service'
export { NotificationService } from '@/lib/services/notification.service'
export { AIService } from '@/lib/services/ai.service'
export type { ParsedRequirements } from '@/lib/services/ai.service'
export { IntegrationService } from '@/lib/services/integration.service'
export { WhatsAppService } from '@/lib/services/whatsapp.service'
export { WorkflowEngineService } from '@/lib/services/workflow-engine.service'
