export type {
  McpJsonSchema,
  McpToolDefinition,
  McpResourceDefinition,
  McpPromptDefinition,
  McpServerMetadata,
  McpServerId,
  McpToolCallRequest,
  McpToolCallResult,
  McpExecutionContext,
  McpServerCapabilities,
  McpServerDefinition,
  McpToolHandlerMap,
  McpToolHandler,
  McpServerInterface,
  McpRegistryInterface,
  McpGatewayInterface,
} from '@/lib/mcp/types'

export type {
  McpContextValidator,
  McpToolAuthorizer,
  McpAuditLogger,
  McpRateLimiter,
  McpMiddleware,
  McpTransportInterface,
  McpClientInterface,
} from '@/lib/mcp/interfaces'

export {
  ALL_MCP_SERVER_DEFINITIONS,
  ALL_MCP_TOOL_NAMES,
  MCP_SERVER_COUNT,
  MCP_TOOL_COUNT,
} from '@/lib/mcp/servers'

export { getMcpGateway, resetMcpGateway, createMcpExecutionContext, McpGateway } from '@/lib/mcp/gateway'

export {
  CRM_TOOLS,
  CRM_SERVER_DEFINITION,
  TALENT_TOOLS,
  TALENT_SERVER_DEFINITION,
  PROJECTS_TOOLS,
  PROJECTS_SERVER_DEFINITION,
  WORKFLOW_TOOLS,
  WORKFLOW_SERVER_DEFINITION,
  FINANCE_TOOLS,
  FINANCE_SERVER_DEFINITION,
  ANALYTICS_TOOLS,
  ANALYTICS_SERVER_DEFINITION,
  KNOWLEDGE_TOOLS,
  KNOWLEDGE_SERVER_DEFINITION,
  NOTIFICATION_TOOLS,
  NOTIFICATION_SERVER_DEFINITION,
  STORAGE_TOOLS,
  STORAGE_SERVER_DEFINITION,
  AI_TOOLS,
  AI_SERVER_DEFINITION,
} from '@/lib/mcp/servers'

export type {
  CrmMcpServerInterface,
  CrmToolName,
  CrmToolInputs,
  TalentMcpServerInterface,
  TalentToolName,
  TalentToolInputs,
  ProjectsMcpServerInterface,
  ProjectsToolName,
  ProjectsToolInputs,
  WorkflowMcpServerInterface,
  WorkflowToolName,
  WorkflowToolInputs,
  FinanceMcpServerInterface,
  FinanceToolName,
  FinanceToolInputs,
  AnalyticsMcpServerInterface,
  AnalyticsToolName,
  AnalyticsToolInputs,
  KnowledgeMcpServerInterface,
  KnowledgeToolName,
  KnowledgeToolInputs,
  NotificationMcpServerInterface,
  NotificationToolName,
  NotificationToolInputs,
  StorageMcpServerInterface,
  StorageToolName,
  StorageToolInputs,
  AiMcpServerInterface,
  AiToolName,
  AiToolInputs,
} from '@/lib/mcp/servers'
