/** Standard API error codes — stable for SDK generation. */
export const ApiErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  NO_TENANT: 'NO_TENANT',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE: 'DUPLICATE',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AI_MATCHING_DISABLED: 'AI_MATCHING_DISABLED',
  AI_MONTHLY_LIMIT_EXCEEDED: 'AI_MONTHLY_LIMIT_EXCEEDED',
  WEBHOOK_INVALID_SIGNATURE: 'WEBHOOK_INVALID_SIGNATURE',
  CRON_UNAUTHORIZED: 'CRON_UNAUTHORIZED',
} as const

export type ApiErrorCode = (typeof ApiErrorCodes)[keyof typeof ApiErrorCodes]

/** HTTP status mapping for standard codes. */
export const API_ERROR_STATUS: Record<ApiErrorCode, number> = {
  UNAUTHORIZED: 401,
  NO_TENANT: 403,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  VALIDATION_ERROR: 400,
  DUPLICATE: 409,
  RATE_LIMITED: 429,
  IDEMPOTENCY_CONFLICT: 409,
  INTERNAL_ERROR: 500,
  AI_MATCHING_DISABLED: 403,
  AI_MONTHLY_LIMIT_EXCEEDED: 429,
  WEBHOOK_INVALID_SIGNATURE: 401,
  CRON_UNAUTHORIZED: 401,
}

export function apiErrorStatus(code: ApiErrorCode): number {
  return API_ERROR_STATUS[code] ?? 400
}
